package encomiendas.views.usuarios;

import encomiendas.controllers.agencias.AgenciaController;
import encomiendas.controllers.usuarios.AdministradorController;
import encomiendas.database.Conexion;
import encomiendas.model.data.agencias.DbAgencia;
import encomiendas.model.data.usuarios.UsuarioRepository;
import encomiendas.model.entity.usuarios.Agencia;
import encomiendas.services.usuarios.UsuarioService;
import encomiendas.views.agencias.ConsultaAgencia;
import encomiendas.views.agencias.ModificarInformacionAgencia;
import encomiendas.views.agencias.NuevaAgencia;
import encomiendas.views.agencias.VerChoferes;
import java.awt.BorderLayout;
import javax.swing.JFrame;

public class MenuAdministrador extends javax.swing.JFrame {

    private ConsultaAgencia frmConsultaAgencia;
    private NuevaAgencia frmNuevaAgencia;
    private ModificarInformacionAgencia frmModificarInformacionAgencia;
    private VerChoferes frmVerChoferes;

    private encomiendas.model.entity.agencias.Agencia modAgencia;
    private DbAgencia modDbAgencia;

    private AgenciaController controller;
    
    Conexion con = new Conexion();
    
    UsuarioRepository usuarioRepository;
    UsuarioService usuarioService;
    AdministradorController administradorController;

    
    public MenuAdministrador() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Lista de usuarios");

        //instancia del controlador
        usuarioRepository = new UsuarioRepository(con.getInstance());
        usuarioService = new UsuarioService(usuarioRepository);
        administradorController = new AdministradorController(this, usuarioService);
        inicializarComponentesAdicionales();
    }
    
        private void inicializarComponentesAdicionales() {
        frmConsultaAgencia = new ConsultaAgencia();
        frmNuevaAgencia = new NuevaAgencia();
        frmModificarInformacionAgencia = new ModificarInformacionAgencia();
        frmVerChoferes = new VerChoferes();
    
        modAgencia = new encomiendas.model.entity.agencias.Agencia();
        modDbAgencia = new DbAgencia();

        controller = new AgenciaController(modAgencia, modDbAgencia, frmConsultaAgencia, frmNuevaAgencia, frmModificarInformacionAgencia, frmVerChoferes);
        controller.iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenúAdministrador = new javax.swing.JPanel();
        jPAdministradorMétodos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLAdministrador = new javax.swing.JLabel();
        jTFUsuarioAdministrador = new javax.swing.JTextField();
        btListaUsuarios = new javax.swing.JButton();
        btIngresoUsuarios = new javax.swing.JButton();
        btActualizarUsuarios = new javax.swing.JButton();
        btActAgencia = new javax.swing.JButton();
        btVerChoferes = new javax.swing.JButton();
        btVerAgencias = new javax.swing.JButton();
        btNuevaAgencia = new javax.swing.JButton();
        jFrameAdministrador = new javax.swing.JPanel();
        jLBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú - Administrador");
        setResizable(false);

        jPMenúAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPAdministradorMétodos.setBackground(new java.awt.Color(0, 0, 0));
        jPAdministradorMétodos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()-2f));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo - copia.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPAdministradorMétodos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 90));

        jLAdministrador.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        jLAdministrador.setText("Administrador:");
        jPAdministradorMétodos.add(jLAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jTFUsuarioAdministrador.setEditable(false);
        jPAdministradorMétodos.add(jTFUsuarioAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, -1));

        btListaUsuarios.setBackground(new java.awt.Color(200, 0, 0));
        btListaUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btListaUsuarios.setText("Lista de Usuarios");
        btListaUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jPAdministradorMétodos.add(btListaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 30));

        btIngresoUsuarios.setBackground(new java.awt.Color(200, 0, 0));
        btIngresoUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btIngresoUsuarios.setText("Ingreso Usuarios");
        btIngresoUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jPAdministradorMétodos.add(btIngresoUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 150, 30));

        btActualizarUsuarios.setBackground(new java.awt.Color(200, 0, 0));
        btActualizarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btActualizarUsuarios.setText("Actualizar Usuarios");
        btActualizarUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btActualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarUsuariosActionPerformed(evt);
            }
        });
        jPAdministradorMétodos.add(btActualizarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, 30));

        btActAgencia.setBackground(new java.awt.Color(200, 0, 0));
        btActAgencia.setForeground(new java.awt.Color(255, 255, 255));
        btActAgencia.setText("Actualizar Agencias");
        btActAgencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btActAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActAgenciaActionPerformed(evt);
            }
        });
        jPAdministradorMétodos.add(btActAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 30));

        btVerChoferes.setBackground(new java.awt.Color(200, 0, 0));
        btVerChoferes.setForeground(new java.awt.Color(255, 255, 255));
        btVerChoferes.setText("Lista Choferes");
        btVerChoferes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btVerChoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerChoferesActionPerformed(evt);
            }
        });
        jPAdministradorMétodos.add(btVerChoferes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 150, 30));

        btVerAgencias.setBackground(new java.awt.Color(200, 0, 0));
        btVerAgencias.setForeground(new java.awt.Color(255, 255, 255));
        btVerAgencias.setText("Lista Agencia");
        btVerAgencias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btVerAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerAgenciasActionPerformed(evt);
            }
        });
        jPAdministradorMétodos.add(btVerAgencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 150, 30));

        btNuevaAgencia.setBackground(new java.awt.Color(200, 0, 0));
        btNuevaAgencia.setForeground(new java.awt.Color(255, 255, 255));
        btNuevaAgencia.setText("Ingreso Agencia");
        btNuevaAgencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btNuevaAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevaAgenciaActionPerformed(evt);
            }
        });
        jPAdministradorMétodos.add(btNuevaAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 150, 30));

        jPMenúAdministrador.add(jPAdministradorMétodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 430));

        jFrameAdministrador.setBackground(new java.awt.Color(37, 37, 61));

        jLBienvenida.setFont(new java.awt.Font("Segoe UI", 3, 44)); // NOI18N
        jLBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jLBienvenida.setText("BIENVENIDO ");

        javax.swing.GroupLayout jFrameAdministradorLayout = new javax.swing.GroupLayout(jFrameAdministrador);
        jFrameAdministrador.setLayout(jFrameAdministradorLayout);
        jFrameAdministradorLayout.setHorizontalGroup(
            jFrameAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameAdministradorLayout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jLBienvenida)
                .addGap(195, 195, 195))
        );
        jFrameAdministradorLayout.setVerticalGroup(
            jFrameAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameAdministradorLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jPMenúAdministrador.add(jFrameAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 690, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenúAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenúAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNuevaAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevaAgenciaActionPerformed
        frmNuevaAgencia.setVisible(true);
        frmNuevaAgencia.setLocationRelativeTo(null);  
        frmNuevaAgencia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btNuevaAgenciaActionPerformed

    private void btActAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActAgenciaActionPerformed
        frmModificarInformacionAgencia.setVisible(true);
        frmModificarInformacionAgencia.setLocationRelativeTo(null);
        frmModificarInformacionAgencia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btActAgenciaActionPerformed

    private void btVerChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerChoferesActionPerformed
        frmVerChoferes.setVisible(true);
        frmVerChoferes.setLocationRelativeTo(null);
        frmVerChoferes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btVerChoferesActionPerformed

    private void btActualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btActualizarUsuariosActionPerformed

    private void btVerAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerAgenciasActionPerformed
        frmConsultaAgencia.setVisible(true);
        frmConsultaAgencia.setLocationRelativeTo(null);  
        frmConsultaAgencia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btVerAgenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btActAgencia;
    public javax.swing.JButton btActualizarUsuarios;
    public javax.swing.JButton btIngresoUsuarios;
    public javax.swing.JButton btListaUsuarios;
    public javax.swing.JButton btNuevaAgencia;
    public javax.swing.JButton btVerAgencias;
    public javax.swing.JButton btVerChoferes;
    private javax.swing.JPanel jFrameAdministrador;
    private javax.swing.JLabel jLAdministrador;
    private javax.swing.JLabel jLBienvenida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPAdministradorMétodos;
    private javax.swing.JPanel jPMenúAdministrador;
    public javax.swing.JTextField jTFUsuarioAdministrador;
    // End of variables declaration//GEN-END:variables
}
