package encomiendas.views.usuarios;

import encomiendas.controllers.almacenamiento.CtrAlmacen;
import encomiendas.controllers.almacenamiento.CtrFichaEncomienda;
import encomiendas.controllers.almacenamiento.CtrSeccion;
import encomiendas.database.Conexion;
import encomiendas.model.data.Agencia.AgenciaRepository;
import encomiendas.model.data.almacenamiento.AlmacenamientoRepository;
import encomiendas.model.data.almacenamiento.FichaEncomiendaRepository;
import encomiendas.model.data.almacenamiento.SeccionRepository;
import encomiendas.model.data.encomiendas.EncomiendaRepository;
import encomiendas.model.data.encomiendas.PaqueteRepository;
import encomiendas.model.data.usuarios.ClienteRepository;
import encomiendas.model.entity.almacenamiento.Almacen;
import encomiendas.model.entity.almacenamiento.FichaEncomienda;
import encomiendas.model.entity.almacenamiento.Seccion;
import encomiendas.model.entity.usuarios.Agencia;
import encomiendas.services.almacen.AlmacenService;
import encomiendas.services.almacen.FichaEncomiendaService;
import encomiendas.services.almacen.SeccionService;
import encomiendas.services.encomiendas.EncomiendaService;
import encomiendas.services.encomiendas.PaqueteService;
import encomiendas.views.almacenamiento.FRMAlmacen;
import encomiendas.views.almacenamiento.NuevaFicha;
import encomiendas.views.encomiendas.JFEncomiendas;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author USER-PC
 */
public class MenuEmpleado extends javax.swing.JFrame {

    public MenuEmpleado() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenuEmpleado = new javax.swing.JPanel();
        jPEmpleadoMétodos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLEmpleado = new javax.swing.JLabel();
        jTFUsuarioEmpleado = new javax.swing.JTextField();
        JTPEmpleado = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPMétodoEditar5 = new javax.swing.JPanel();
        jPAEditarUsuarios4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFTNombresE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFApellidoE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFCedulaE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCorreoE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFTelefonoE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLFotoPerfilE = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFUsuarioE = new javax.swing.JTextField();
        btECredencial = new javax.swing.JButton();
        btEPerfil = new javax.swing.JButton();
        jTFContrasenia = new javax.swing.JTextField();
        jBCambiarFoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPMétodoEditar2 = new javax.swing.JPanel();
        jPAEditarUsuarios2 = new javax.swing.JPanel();
        jLTablaUsuarios2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbEClientes = new javax.swing.JTable();
        btEClientes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPMétodoEditar3 = new javax.swing.JPanel();
        jPAEditarUsuarios3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTbConductores = new javax.swing.JTable();
        jLTablaUsuarios3 = new javax.swing.JLabel();
        btEConductores = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPMétodoEditar4 = new javax.swing.JPanel();
        jPAEEcomiendas = new javax.swing.JPanel();
        btnAbrirEncomiendas = new javax.swing.JButton();
        JPAlmacenamiento = new javax.swing.JPanel();
        btnVerAlmacen = new javax.swing.JButton();
        btnAlmacenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú - Empleado");
        setResizable(false);

        jPMenuEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPEmpleadoMétodos.setBackground(new java.awt.Color(0, 0, 0));
        jPEmpleadoMétodos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()-2f));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo - copia.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPEmpleadoMétodos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 90));

        jLEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jLEmpleado.setText("Empleado:");
        jPEmpleadoMétodos.add(jLEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jTFUsuarioEmpleado.setEditable(false);
        jTFUsuarioEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTFUsuarioEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPEmpleadoMétodos.add(jTFUsuarioEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, -1));

        jPMenuEmpleado.add(jPEmpleadoMétodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 440));

        JTPEmpleado.setBackground(new java.awt.Color(200, 0, 0));
        JTPEmpleado.setForeground(new java.awt.Color(255, 255, 255));

        jPMétodoEditar5.setBackground(new java.awt.Color(204, 0, 51));
        jPMétodoEditar5.setMinimumSize(new java.awt.Dimension(690, 430));
        jPMétodoEditar5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombres:");

        jFTNombresE.setEditable(false);

        jLabel3.setText("Apellido:");

        jTFApellidoE.setEditable(false);

        jLabel4.setText("Cédula:");

        jTFCedulaE.setEditable(false);

        jLabel5.setText("Correo:");

        jTFCorreoE.setEditable(false);

        jLabel6.setText("Teléfono:");

        jTFTelefonoE.setEditable(false);

        jLabel9.setText("Foto de perfil:");

        jLFotoPerfilE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Cuenta");

        jLabel8.setText("Usuario:");

        jLabel10.setText("Contraseña:");

        jTFUsuarioE.setEditable(false);

        btECredencial.setText("Ver Credenciales");

        btEPerfil.setText("Mostrar");

        jTFContrasenia.setEditable(false);

        jBCambiarFoto.setText("Cambiar Foto");

        javax.swing.GroupLayout jPAEditarUsuarios4Layout = new javax.swing.GroupLayout(jPAEditarUsuarios4);
        jPAEditarUsuarios4.setLayout(jPAEditarUsuarios4Layout);
        jPAEditarUsuarios4Layout.setHorizontalGroup(
            jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAEditarUsuarios4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48)
                .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPAEditarUsuarios4Layout.createSequentialGroup()
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTNombresE)
                            .addComponent(jTFApellidoE)
                            .addComponent(jTFCedulaE)
                            .addComponent(jTFCorreoE)
                            .addComponent(jTFTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPAEditarUsuarios4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBCambiarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLFotoPerfilE, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPAEditarUsuarios4Layout.createSequentialGroup()
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFUsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btECredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
            .addGroup(jPAEditarUsuarios4Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(btEPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPAEditarUsuarios4Layout.setVerticalGroup(
            jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAEditarUsuarios4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAEditarUsuarios4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLFotoPerfilE, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPAEditarUsuarios4Layout.createSequentialGroup()
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFTNombresE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTFCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTFTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCambiarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAEditarUsuarios4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(23, 23, 23)
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTFUsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPAEditarUsuarios4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTFContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAEditarUsuarios4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btECredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        jPMétodoEditar5.add(jPAEditarUsuarios4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 680, 390));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoEditar5, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPMétodoEditar5, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        JTPEmpleado.addTab(" Perfil", jPanel1);

        jPMétodoEditar2.setBackground(new java.awt.Color(204, 0, 51));
        jPMétodoEditar2.setMinimumSize(new java.awt.Dimension(690, 430));
        jPMétodoEditar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTablaUsuarios2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLTablaUsuarios2.setText("Lista de Clientes");

        jTbEClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombres", "Apellidos", "Correo", "Teléfono", "Rol", "Dirección ", "Ciudad", "Teléfono Secundario", "TÍpo Licencia ", "Estado", "Id Agencia "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTbEClientes);

        btEClientes.setText("Mostrar");

        javax.swing.GroupLayout jPAEditarUsuarios2Layout = new javax.swing.GroupLayout(jPAEditarUsuarios2);
        jPAEditarUsuarios2.setLayout(jPAEditarUsuarios2Layout);
        jPAEditarUsuarios2Layout.setHorizontalGroup(
            jPAEditarUsuarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAEditarUsuarios2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAEditarUsuarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAEditarUsuarios2Layout.createSequentialGroup()
                        .addComponent(jLTablaUsuarios2)
                        .addGap(138, 138, 138)
                        .addComponent(btEClientes))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPAEditarUsuarios2Layout.setVerticalGroup(
            jPAEditarUsuarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAEditarUsuarios2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPAEditarUsuarios2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTablaUsuarios2)
                    .addComponent(btEClientes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPMétodoEditar2.add(jPAEditarUsuarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 680, 390));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoEditar2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPMétodoEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        JTPEmpleado.addTab("Clientes", jPanel2);

        jPMétodoEditar3.setBackground(new java.awt.Color(204, 0, 51));
        jPMétodoEditar3.setMinimumSize(new java.awt.Dimension(690, 430));
        jPMétodoEditar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbConductores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombres", "Apellidos", "Correo", "Teléfono", "Rol", "Dirección ", "Ciudad", "Teléfono Secundario", "TÍpo Licencia ", "Estado", "Id Agencia "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTbConductores);

        jLTablaUsuarios3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLTablaUsuarios3.setText("Lista de Conductores");

        btEConductores.setText("Mostrar");

        javax.swing.GroupLayout jPAEditarUsuarios3Layout = new javax.swing.GroupLayout(jPAEditarUsuarios3);
        jPAEditarUsuarios3.setLayout(jPAEditarUsuarios3Layout);
        jPAEditarUsuarios3Layout.setHorizontalGroup(
            jPAEditarUsuarios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAEditarUsuarios3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAEditarUsuarios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPAEditarUsuarios3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPAEditarUsuarios3Layout.createSequentialGroup()
                        .addComponent(jLTablaUsuarios3)
                        .addGap(104, 104, 104)
                        .addComponent(btEConductores)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPAEditarUsuarios3Layout.setVerticalGroup(
            jPAEditarUsuarios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAEditarUsuarios3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPAEditarUsuarios3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTablaUsuarios3)
                    .addComponent(btEConductores))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPMétodoEditar3.add(jPAEditarUsuarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 680, 390));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoEditar3, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoEditar3, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        JTPEmpleado.addTab("Conductores", jPanel3);

        jPMétodoEditar4.setBackground(new java.awt.Color(204, 0, 51));
        jPMétodoEditar4.setMinimumSize(new java.awt.Dimension(690, 430));
        jPMétodoEditar4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbrirEncomiendas.setText("Abrir encomiendas");
        btnAbrirEncomiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirEncomiendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAEEcomiendasLayout = new javax.swing.GroupLayout(jPAEEcomiendas);
        jPAEEcomiendas.setLayout(jPAEEcomiendasLayout);
        jPAEEcomiendasLayout.setHorizontalGroup(
            jPAEEcomiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAEEcomiendasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnAbrirEncomiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
        );
        jPAEEcomiendasLayout.setVerticalGroup(
            jPAEEcomiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAEEcomiendasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnAbrirEncomiendas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        jPMétodoEditar4.add(jPAEEcomiendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 680, 390));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoEditar4, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoEditar4, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        JTPEmpleado.addTab("Encomiendas", jPanel4);

        btnVerAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerAlmacen.setText("Ver almacén");
        btnVerAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlmacenActionPerformed(evt);
            }
        });

        btnAlmacenar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAlmacenar.setText("Almacenar");
        btnAlmacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPAlmacenamientoLayout = new javax.swing.GroupLayout(JPAlmacenamiento);
        JPAlmacenamiento.setLayout(JPAlmacenamientoLayout);
        JPAlmacenamientoLayout.setHorizontalGroup(
            JPAlmacenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(JPAlmacenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPAlmacenamientoLayout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(btnVerAlmacen)
                    .addGap(73, 73, 73)
                    .addComponent(btnAlmacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(182, Short.MAX_VALUE)))
        );
        JPAlmacenamientoLayout.setVerticalGroup(
            JPAlmacenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(JPAlmacenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPAlmacenamientoLayout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addGroup(JPAlmacenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVerAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlmacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(178, Short.MAX_VALUE)))
        );

        JTPEmpleado.addTab("Almacenamiento", JPAlmacenamiento);

        jPMenuEmpleado.add(JTPEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenuEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenuEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirEncomiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirEncomiendasActionPerformed
        JFEncomiendas encomiendas = new JFEncomiendas();

        encomiendas.setVisible(true);
        encomiendas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnAbrirEncomiendasActionPerformed

    private void btnVerAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlmacenActionPerformed
        Almacen almacen = new Almacen();
        FRMAlmacen frmAlm = new FRMAlmacen();
        NuevaFicha frmFicha = new NuevaFicha();
        Agencia agencia =  new  Agencia();
        Seccion seccion = new Seccion();
        FichaEncomienda ficha = new FichaEncomienda();
        Connection connection = Conexion.getInstance();

        SeccionRepository seccionRepository = new SeccionRepository(connection);
        FichaEncomiendaRepository fichaRepository = new FichaEncomiendaRepository(connection);
        AlmacenamientoRepository almacenRepository = new AlmacenamientoRepository(connection);
        EncomiendaRepository encomiendaRepo =  new EncomiendaRepository(connection);
        SeccionService seccionService = new SeccionService(seccionRepository);
        AlmacenService almacenService =  new AlmacenService(almacenRepository);
        FichaEncomiendaService fichaService =  new FichaEncomiendaService(fichaRepository);
        AgenciaRepository agenciaRepo = new AgenciaRepository(connection);
        ClienteRepository clienteRepository = new ClienteRepository(connection);
        PaqueteRepository paqueteRepository = new PaqueteRepository(connection);
        PaqueteService paqueteService = new PaqueteService(paqueteRepository);
        
        EncomiendaService encoService = new EncomiendaService(encomiendaRepo,clienteRepository,agenciaRepo,paqueteService);
        
        try {
            CtrSeccion ctrSeccion =  new CtrSeccion(seccion,seccionService,frmAlm,frmFicha);
            CtrAlmacen crtAlm = new CtrAlmacen(frmAlm,almacenService,agenciaRepo);
            crtAlm.cargarAlmacenes();
            crtAlm.cargarAgencias();
            ctrSeccion.cargarSecciones();
            CtrFichaEncomienda ctrFicha = new CtrFichaEncomienda(ficha,fichaService,frmFicha,frmAlm,seccionService,encoService);
            ctrFicha.cargarEncomiendas();
        } catch (SQLException ex) {
            
        }
        
        frmAlm.setVisible(true);

    }//GEN-LAST:event_btnVerAlmacenActionPerformed

    private void btnAlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenarActionPerformed
        Almacen almacen = new Almacen();
        FRMAlmacen frmAlm = new FRMAlmacen();
        NuevaFicha frmFicha = new NuevaFicha();
        Agencia agencia =  new  Agencia();
        Seccion seccion = new Seccion();
        FichaEncomienda ficha = new FichaEncomienda();
        Connection connection = Conexion.getInstance();

        SeccionRepository seccionRepository = new SeccionRepository(connection);
        FichaEncomiendaRepository fichaRepository = new FichaEncomiendaRepository(connection);
        AlmacenamientoRepository almacenRepository = new AlmacenamientoRepository(connection);
        EncomiendaRepository encomiendaRepo =  new EncomiendaRepository(connection);
        SeccionService seccionService = new SeccionService(seccionRepository);
        AlmacenService almacenService =  new AlmacenService(almacenRepository);
        FichaEncomiendaService fichaService =  new FichaEncomiendaService(fichaRepository);
        AgenciaRepository agenciaRepo = new AgenciaRepository(connection);
        ClienteRepository clienteRepository = new ClienteRepository(connection);
        PaqueteRepository paqueteRepository = new PaqueteRepository(connection);
        PaqueteService paqueteService = new PaqueteService(paqueteRepository);
        
        EncomiendaService encoService = new EncomiendaService(encomiendaRepo,clienteRepository,agenciaRepo,paqueteService);
        
        try {
            CtrSeccion ctrSeccion =  new CtrSeccion(seccion,seccionService,frmAlm,frmFicha);
            CtrAlmacen crtAlm = new CtrAlmacen(frmAlm,almacenService,agenciaRepo);
            crtAlm.cargarAlmacenes();
            crtAlm.cargarAgencias();
            ctrSeccion.cargarSecciones();
            CtrFichaEncomienda ctrFicha = new CtrFichaEncomienda(ficha,fichaService,frmFicha,frmAlm,seccionService,encoService);
            ctrFicha.cargarEncomiendas();
        } catch (SQLException ex) {
            
        }
        
        frmFicha.setVisible(true);
    }//GEN-LAST:event_btnAlmacenarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPAlmacenamiento;
    public javax.swing.JTabbedPane JTPEmpleado;
    public javax.swing.JButton btEClientes;
    public javax.swing.JButton btEConductores;
    public javax.swing.JButton btECredencial;
    public javax.swing.JButton btEPerfil;
    public javax.swing.JButton btnAbrirEncomiendas;
    public javax.swing.JButton btnAlmacenar;
    public javax.swing.JButton btnVerAlmacen;
    public javax.swing.JButton jBCambiarFoto;
    public javax.swing.JTextField jFTNombresE;
    public javax.swing.JLabel jLEmpleado;
    public javax.swing.JLabel jLFotoPerfilE;
    private javax.swing.JLabel jLTablaUsuarios2;
    private javax.swing.JLabel jLTablaUsuarios3;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAEEcomiendas;
    private javax.swing.JPanel jPAEditarUsuarios2;
    private javax.swing.JPanel jPAEditarUsuarios3;
    private javax.swing.JPanel jPAEditarUsuarios4;
    public javax.swing.JPanel jPEmpleadoMétodos;
    private javax.swing.JPanel jPMenuEmpleado;
    private javax.swing.JPanel jPMétodoEditar2;
    private javax.swing.JPanel jPMétodoEditar3;
    private javax.swing.JPanel jPMétodoEditar4;
    private javax.swing.JPanel jPMétodoEditar5;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextField jTFApellidoE;
    public javax.swing.JTextField jTFCedulaE;
    public javax.swing.JTextField jTFContrasenia;
    public javax.swing.JTextField jTFCorreoE;
    public javax.swing.JTextField jTFTelefonoE;
    public javax.swing.JTextField jTFUsuarioE;
    public javax.swing.JTextField jTFUsuarioEmpleado;
    public javax.swing.JTable jTbConductores;
    public javax.swing.JTable jTbEClientes;
    // End of variables declaration//GEN-END:variables
}
