/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package encomiendas.views.usuarios;

/**
 *
 * @author USER-PC
 */
public class PanelAVisualizarUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form PanelPerfil
     */
    public PanelAVisualizarUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMétodoVisualizar = new javax.swing.JPanel();
        jPAVisualizarUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jLRol = new javax.swing.JLabel();
        jLSelecciónMétodoBusqueda = new javax.swing.JLabel();
        jCBMétodoBusqueda = new javax.swing.JComboBox<>();
        jTFMétodoBusqueda = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLTablaUsuarios = new javax.swing.JLabel();
        jCBRol = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(690, 430));
        setPreferredSize(new java.awt.Dimension(690, 430));

        jPMétodoVisualizar.setBackground(new java.awt.Color(204, 0, 51));
        jPMétodoVisualizar.setMinimumSize(new java.awt.Dimension(690, 430));
        jPMétodoVisualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Usuario", "Cédula", "Teléfono Principal", "Nombres", "Apellidos", "Correo", "Teléfono", "Rol", "Dirección ", "Ciudad", "Teléfono Secundario", "TÍpo Licencia ", "Activo ", "Id Agencia "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        jLRol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLRol.setText("Rol:");

        jLSelecciónMétodoBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLSelecciónMétodoBusqueda.setText("Selección método de busqueda:");

        jCBMétodoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCBMétodoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Usuario", "Cédula" }));

        jTFMétodoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jBBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLTablaUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLTablaUsuarios.setText("Tabla de Usuarios:");

        jCBRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado", "Conductor" }));

        javax.swing.GroupLayout jPAVisualizarUsuariosLayout = new javax.swing.GroupLayout(jPAVisualizarUsuarios);
        jPAVisualizarUsuarios.setLayout(jPAVisualizarUsuariosLayout);
        jPAVisualizarUsuariosLayout.setHorizontalGroup(
            jPAVisualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAVisualizarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAVisualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAVisualizarUsuariosLayout.createSequentialGroup()
                        .addGroup(jPAVisualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAVisualizarUsuariosLayout.createSequentialGroup()
                                .addComponent(jLSelecciónMétodoBusqueda)
                                .addGap(18, 18, 18)
                                .addComponent(jCBMétodoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFMétodoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPAVisualizarUsuariosLayout.createSequentialGroup()
                        .addGroup(jPAVisualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAVisualizarUsuariosLayout.createSequentialGroup()
                                .addComponent(jLRol)
                                .addGap(18, 18, 18)
                                .addComponent(jCBRol, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLTablaUsuarios))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPAVisualizarUsuariosLayout.setVerticalGroup(
            jPAVisualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAVisualizarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAVisualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRol)
                    .addComponent(jCBRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAVisualizarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSelecciónMétodoBusqueda)
                    .addComponent(jCBMétodoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFMétodoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLTablaUsuarios)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPMétodoVisualizar.add(jPAVisualizarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 680, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JComboBox<String> jCBMétodoBusqueda;
    private javax.swing.JComboBox<String> jCBRol;
    private javax.swing.JLabel jLRol;
    private javax.swing.JLabel jLSelecciónMétodoBusqueda;
    private javax.swing.JLabel jLTablaUsuarios;
    private javax.swing.JPanel jPAVisualizarUsuarios;
    private javax.swing.JPanel jPMétodoVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFMétodoBusqueda;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
