/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package encomiendas.views.usuarios;

/**
 *
 * @author Atik
 */
public class PanelEEncomiendas extends javax.swing.JPanel {

    /**
     * Creates new form PanelEEncomiendas
     */
    public PanelEEncomiendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMétodoEditar = new javax.swing.JPanel();
        jPAEditarUsuarios = new javax.swing.JPanel();

        jPMétodoEditar.setBackground(new java.awt.Color(204, 0, 51));
        jPMétodoEditar.setMinimumSize(new java.awt.Dimension(690, 430));
        jPMétodoEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPAEditarUsuariosLayout = new javax.swing.GroupLayout(jPAEditarUsuarios);
        jPAEditarUsuarios.setLayout(jPAEditarUsuariosLayout);
        jPAEditarUsuariosLayout.setHorizontalGroup(
            jPAEditarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPAEditarUsuariosLayout.setVerticalGroup(
            jPAEditarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPMétodoEditar.add(jPAEditarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 680, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMétodoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPAEditarUsuarios;
    private javax.swing.JPanel jPMétodoEditar;
    // End of variables declaration//GEN-END:variables
}
