/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encomiendas.views.almacenamiento;

import encomiendas.controllers.almacenamiento.CtrAlmacen;
import encomiendas.controllers.almacenamiento.CtrFichaEncomienda;
import encomiendas.controllers.almacenamiento.CtrSeccion;
import encomiendas.database.Conexion;
import encomiendas.model.data.Agencia.AgenciaRepository;
import encomiendas.model.data.almacenamiento.AlmacenamientoRepository;
import encomiendas.model.data.almacenamiento.FichaEncomiendaRepository;
import encomiendas.model.data.almacenamiento.SeccionRepository;
import encomiendas.model.data.encomiendas.EncomiendaRepository;
import encomiendas.model.data.encomiendas.PaqueteRepository;
import encomiendas.model.data.usuarios.ClienteRepository;
import encomiendas.model.entity.almacenamiento.Almacen;
import encomiendas.model.entity.almacenamiento.FichaEncomienda;
import encomiendas.model.entity.almacenamiento.Seccion;
import encomiendas.model.entity.usuarios.Agencia;
import encomiendas.services.almacen.AlmacenService;
import encomiendas.services.almacen.FichaEncomiendaService;
import encomiendas.services.almacen.SeccionService;
import encomiendas.services.encomiendas.EncomiendaService;
import encomiendas.services.encomiendas.PaqueteService;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



public class Bienvenido extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Bienvenido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lbNombreE = new javax.swing.JLabel();
        btnAlmacenar = new javax.swing.JButton();
        btnVerAlmacen = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 255, 51));

        jPanel1.setBackground(new java.awt.Color(192, 223, 255));

        lbNombreE.setBackground(new java.awt.Color(102, 102, 102));
        lbNombreE.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbNombreE.setText("Almacenamiento");

        btnAlmacenar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAlmacenar.setText("Almacenar");
        btnAlmacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenarActionPerformed(evt);
            }
        });

        btnVerAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerAlmacen.setText("Ver almacén");
        btnVerAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlmacenActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnVerAlmacen)
                        .addGap(73, 73, 73)
                        .addComponent(btnAlmacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbNombreE)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lbNombreE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlmacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlmacenActionPerformed
        Almacen almacen = new Almacen();
        FRMAlmacen frmAlm = new FRMAlmacen();
        NuevaFicha frmFicha = new NuevaFicha();
        Agencia agencia =  new  Agencia();
        Seccion seccion = new Seccion();
        FichaEncomienda ficha = new FichaEncomienda();
        Connection connection = Conexion.getInstance();

        SeccionRepository seccionRepository = new SeccionRepository(connection);
        FichaEncomiendaRepository fichaRepository = new FichaEncomiendaRepository(connection);
        AlmacenamientoRepository almacenRepository = new AlmacenamientoRepository(connection);
        EncomiendaRepository encomiendaRepo =  new EncomiendaRepository(connection);
        SeccionService seccionService = new SeccionService(seccionRepository);
        AlmacenService almacenService =  new AlmacenService(almacenRepository);
        FichaEncomiendaService fichaService =  new FichaEncomiendaService(fichaRepository);
        AgenciaRepository agenciaRepo = new AgenciaRepository(connection);
        ClienteRepository clienteRepository = new ClienteRepository(connection);
        PaqueteRepository paqueteRepository = new PaqueteRepository(connection);
        PaqueteService paqueteService = new PaqueteService(paqueteRepository);
        
        EncomiendaService encoService = new EncomiendaService(encomiendaRepo,clienteRepository,agenciaRepo,paqueteService);
        
        
        //FichaEncomienda ficha, FichaEncomiendaService dbFicha, NuevaFicha frmFicha,FRMAlmacen frmALM,SeccionService dbSeccion
        //Seccion Sec, SeccionService dbSec, FRMAlmacen frmAlm, NuevaFicha frmFicha) {
        CtrSeccion ctrSeccion =  new CtrSeccion(seccion,seccionService,frmAlm,frmFicha);
        CtrAlmacen  crtAlm = null;
        try {
            crtAlm = new CtrAlmacen(frmAlm,almacenService,agenciaRepo);
            crtAlm.cargarAlmacenes();
            crtAlm.cargarAgencias();
            ctrSeccion.cargarSecciones();
        } catch (SQLException ex) {
            Logger.getLogger(Bienvenido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        CtrFichaEncomienda ctrFicha = new CtrFichaEncomienda(ficha,fichaService,frmFicha,frmAlm,seccionService,encoService);
        try {
            ctrFicha.cargarEncomiendas();
        } catch (SQLException ex) {
            Logger.getLogger(Bienvenido.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmAlm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVerAlmacenActionPerformed

    private void btnAlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenarActionPerformed
        Almacen almacen = new Almacen();
        FRMAlmacen frmAlm = new FRMAlmacen();
        NuevaFicha frmFicha = new NuevaFicha();
        Agencia agencia =  new  Agencia();
        Seccion seccion = new Seccion();
        FichaEncomienda ficha = new FichaEncomienda();
        Connection connection = Conexion.getInstance();

        SeccionRepository seccionRepository = new SeccionRepository(connection);
        FichaEncomiendaRepository fichaRepository = new FichaEncomiendaRepository(connection);
        AlmacenamientoRepository almacenRepository = new AlmacenamientoRepository(connection);
        EncomiendaRepository encomiendaRepo =  new EncomiendaRepository(connection);
        SeccionService seccionService = new SeccionService(seccionRepository);
        AlmacenService almacenService =  new AlmacenService(almacenRepository);
        FichaEncomiendaService fichaService =  new FichaEncomiendaService(fichaRepository);
        AgenciaRepository agenciaRepo = new AgenciaRepository(connection);
        ClienteRepository clienteRepository = new ClienteRepository(connection);
        PaqueteRepository paqueteRepository = new PaqueteRepository(connection);
        PaqueteService paqueteService = new PaqueteService(paqueteRepository);
        
        EncomiendaService encoService = new EncomiendaService(encomiendaRepo,clienteRepository,agenciaRepo,paqueteService);
        CtrSeccion ctrSeccion =  new CtrSeccion(seccion,seccionService,frmAlm,frmFicha);
        try {
            ctrSeccion.cargarSecciones();
        } catch (SQLException ex) {
            Logger.getLogger(Bienvenido.class.getName()).log(Level.SEVERE, null, ex);
        }
        CtrAlmacen  crtAlm = null;
        try {
            crtAlm = new CtrAlmacen(frmAlm,almacenService,agenciaRepo);
            crtAlm.cargarAlmacenes();
            crtAlm.cargarAgencias();
            
        } catch (SQLException ex) {
            Logger.getLogger(Bienvenido.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
        CtrFichaEncomienda ctrFicha = new CtrFichaEncomienda(ficha,fichaService,frmFicha,frmAlm,seccionService,encoService);
        try {
            ctrFicha.cargarEncomiendas();
        } catch (SQLException ex) {
            Logger.getLogger(Bienvenido.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Si entre a boton");
        NuevaFicha nuevaFicha = new NuevaFicha();
        nuevaFicha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlmacenarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
   
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAlmacenar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVerAlmacen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbNombreE;
    // End of variables declaration//GEN-END:variables

    private void NuevaFicha() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
