/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encomiendas.views.transporte;

import encomiendas.controllers.transporte.RutaController;
import encomiendas.database.Conexion;
import encomiendas.model.data.transporte.RutaRepository;
import encomiendas.model.entity.transporte.Ruta;
import encomiendas.services.transporte.RutaService;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class JFRuta extends javax.swing.JFrame {

    private Conexion con = new Conexion();
    private RutaController rutaController;
    private RutaRepository rutaRepository;
    private RutaService rutaService;
    private int idRutaActualizar;

    /**
     * Creates new form JFOpcionRuta
     */
    public JFRuta() {
        initComponents();
        cmbTipoRuta.setSelectedIndex(-1);
        rutaRepository = new RutaRepository(con.getInstance());
        rutaService = new RutaService(rutaRepository);
        rutaController = new RutaController(rutaService);
        jTabbedPane1.setEnabledAt(3, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmbTipoRuta = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtListaParadas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelDatos1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdRuta = new javax.swing.JTextField();
        btnBuscarRuta = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbRuta = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRutasCompletas = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        panelEditar = new javax.swing.JPanel();
        jpanelEditarDatos = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cmbEditTipoRuta = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtEditListaParadas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEditDescripcion = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnAgregarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruta"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        cmbTipoRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interprovincial", "Local" }));
        cmbTipoRuta.setSelectedItem(-1);
        cmbTipoRuta.setAutoscrolls(true);
        cmbTipoRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbTipoRutaMouseReleased(evt);
            }
        });
        cmbTipoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoRutaActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo de ruta");

        txtListaParadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtListaParadasActionPerformed(evt);
            }
        });

        jLabel15.setText("Lista de paradas");

        jLabel16.setText("Descripcion");

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoRuta, 0, 501, Short.MAX_VALUE)
                    .addComponent(txtListaParadas)
                    .addComponent(txtDescripcion))
                .addGap(26, 26, 26))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(txtListaParadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(cmbTipoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        panelDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruta"));

        jLabel1.setText("ID");

        btnBuscarRuta.setText("Buscar");
        btnBuscarRuta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBuscarRuta.setContentAreaFilled(false);
        btnBuscarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatos1Layout = new javax.swing.GroupLayout(panelDatos1);
        panelDatos1.setLayout(panelDatos1Layout);
        panelDatos1Layout.setHorizontalGroup(
            panelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(txtIdRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnBuscarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatos1Layout.setVerticalGroup(
            panelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(panelDatos1Layout.createSequentialGroup()
                .addComponent(btnBuscarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbRuta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tbRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRutaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbRuta);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tablaRutasCompletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaRutasCompletas);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnEditar.setContentAreaFilled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar", jPanel3);

        jpanelEditarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar ruta"));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        cmbEditTipoRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interprovincial", "Local" }));
        cmbEditTipoRuta.setSelectedItem(-1);
        cmbEditTipoRuta.setAutoscrolls(true);
        cmbEditTipoRuta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        cmbEditTipoRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbEditTipoRutaMouseReleased(evt);
            }
        });
        cmbEditTipoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditTipoRutaActionPerformed(evt);
            }
        });

        jLabel14.setText("Tipo de ruta");

        txtEditListaParadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditListaParadasActionPerformed(evt);
            }
        });

        jLabel17.setText("Lista de paradas");

        jLabel18.setText("Descripcion");

        txtEditDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEditTipoRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEditListaParadas)
                    .addComponent(txtEditDescripcion))
                .addGap(26, 26, 26))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtEditDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17))
                    .addComponent(txtEditListaParadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cmbEditTipoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAgregarCambios.setText("Guardar");
        btnAgregarCambios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAgregarCambios.setContentAreaFilled(false);
        btnAgregarCambios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelEditarDatosLayout = new javax.swing.GroupLayout(jpanelEditarDatos);
        jpanelEditarDatos.setLayout(jpanelEditarDatosLayout);
        jpanelEditarDatosLayout.setHorizontalGroup(
            jpanelEditarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEditarDatosLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 363, Short.MAX_VALUE))
            .addGroup(jpanelEditarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpanelEditarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelEditarDatosLayout.createSequentialGroup()
                    .addContainerGap(343, Short.MAX_VALUE)
                    .addComponent(btnAgregarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(212, 212, 212)))
        );
        jpanelEditarDatosLayout.setVerticalGroup(
            jpanelEditarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelEditarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jpanelEditarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelEditarDatosLayout.createSequentialGroup()
                    .addContainerGap(214, Short.MAX_VALUE)
                    .addComponent(btnAgregarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)))
        );

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelEditarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelEditarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editar", panelEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRutaMouseClicked

    }//GEN-LAST:event_tbRutaMouseClicked

    private void btnBuscarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutaActionPerformed
        int idRuta = Integer.parseInt(txtIdRuta.getText());
        try {

            Ruta ruta = rutaController.obtenerRuta(idRuta);
            cargarTabla(ruta);

        } catch (SQLException ex) {
            Logger.getLogger(JFRuta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarRutaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String descripcion = txtDescripcion.getText();
        String paradas = txtListaParadas.getText();
        String tipoRuta = (String) cmbTipoRuta.getSelectedItem();
        boolean bTipoRuta;
        if (tipoRuta.equals("Interprovincial")) {
            bTipoRuta = true;
        } else {
            bTipoRuta = false;
        }
        Ruta ruta = new Ruta();
        ruta.setDescripcion(descripcion);
        ruta.setParadas(paradas);
        ruta.setEsInterprovincial(bTipoRuta);
        try {
            rutaController.crearRuta(ruta);
            JOptionPane.showMessageDialog(null, "Ruta agregada correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
        } catch (SQLException ex) {
            Logger.getLogger(JFRuta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtListaParadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtListaParadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListaParadasActionPerformed

    private void cmbTipoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoRutaActionPerformed

    }//GEN-LAST:event_cmbTipoRutaActionPerformed

    private void cmbTipoRutaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTipoRutaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoRutaMouseReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (tablaRutasCompletas.getRowCount() > 0) {
            //se haya seleccionado una fila dado que se puede seleccionar de 0 registros en adelante
            if (tablaRutasCompletas.getSelectedRow() != -1) {
                jTabbedPane1.setEnabledAt(3, true);
                jTabbedPane1.setSelectedIndex(3);
                jTabbedPane1.setEnabledAt(0, false);
                jTabbedPane1.setEnabledAt(1, false);
                jTabbedPane1.setEnabledAt(2, false);

                idRutaActualizar = Integer.parseInt(String.valueOf(tablaRutasCompletas.getValueAt(tablaRutasCompletas.getSelectedRow(), 0)));
                cargarRuta(idRutaActualizar);

            } else {
                JOptionPane.showMessageDialog(null, "No hay nada para editar en la tabla", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se selecciono ninguna ruta", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        // Obtener el índice de la pestaña seleccionada
        int selectedIndex = jTabbedPane1.getSelectedIndex();
        if (selectedIndex == 2) {
            cargarRutasCompletas();  // Llama a la función para cargar la tabla
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void cmbEditTipoRutaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEditTipoRutaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEditTipoRutaMouseReleased

    private void cmbEditTipoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditTipoRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEditTipoRutaActionPerformed

    private void txtEditListaParadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditListaParadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditListaParadasActionPerformed

    private void txtEditDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditDescripcionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCambiosActionPerformed
        try {
            // TODO add your handling code here
            Ruta rutaActualizar = new Ruta();
            rutaActualizar.setDescripcion(txtEditDescripcion.getText());
            rutaActualizar.setParadas(txtEditListaParadas.getText());
            String tipoRuta = (String) cmbEditTipoRuta.getSelectedItem();
            if (tipoRuta.equals("Interprovincial")) {
                rutaActualizar.setEsInterprovincial(true);
            } else {
                rutaActualizar.setEsInterprovincial(false);
            }
            rutaController.actualizarRuta(idRutaActualizar, rutaActualizar);
            JOptionPane.showMessageDialog(null, "Ruta actualizada correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
            jTabbedPane1.setEnabledAt(3, false);
            jTabbedPane1.setSelectedIndex(2);
            jTabbedPane1.setEnabledAt(0, true);
            jTabbedPane1.setEnabledAt(1, true);
            jTabbedPane1.setEnabledAt(2, true);

        } catch (SQLException ex) {
            Logger.getLogger(JFRuta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAgregarCambiosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (tablaRutasCompletas.getRowCount() > 0) {
            //se haya seleccionado una fila dado que se puede seleccionar de 0 registros en adelante
            if (tablaRutasCompletas.getSelectedRow() != -1) {
                try {
                    idRutaActualizar = Integer.parseInt(String.valueOf(tablaRutasCompletas.getValueAt(tablaRutasCompletas.getSelectedRow(), 0)));
                    rutaController.eliminarRuta(idRutaActualizar);
                    JOptionPane.showMessageDialog(null, "Ruta eliminada correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);
                    cargarRutasCompletas();

                } catch (SQLException ex) {
                    Logger.getLogger(JFRuta.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay nada para eliminar en la tabla", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se selecciono ninguna ruta", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarCambios;
    private javax.swing.JButton btnBuscarRuta;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    public javax.swing.JComboBox<String> cmbEditTipoRuta;
    public javax.swing.JComboBox<String> cmbTipoRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpanelEditarDatos;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelDatos1;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JTable tablaRutasCompletas;
    public javax.swing.JTable tbRuta;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtEditDescripcion;
    public javax.swing.JTextField txtEditListaParadas;
    private javax.swing.JTextField txtIdRuta;
    public javax.swing.JTextField txtListaParadas;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        txtDescripcion.setText("");
        txtListaParadas.setText("");
        cmbTipoRuta.setSelectedIndex(-1);
    }

    private void cargarTabla(Ruta ruta) {

        DefaultTableModel modeloTabla = new DefaultTableModel() {
            //filas y columnas no sean editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        //nombres de las columnas
        String titulos[] = {"ID", "Descripción", "Paradas", "Es Interprovincial"};
        //seteamos las columnas
        modeloTabla.setColumnIdentifiers(titulos);
        // Crear un objeto con los valores de la ruta
        Object[] objeto = {ruta.getId(), ruta.getDescripcion(), ruta.getParadas(), ruta.isEsInterprovincial()};

        // Agregar la fila al modelo de la tabla
        modeloTabla.addRow(objeto);

        // Establecer el modelo de la tabla
        tbRuta.setModel(modeloTabla);
    }

    private void cargarRutasCompletas() {

        try {
            DefaultTableModel modeloTabla = new DefaultTableModel() {
                //filas y columnas no sean editables
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            //nombres de las columnas
            String titulos[] = {"ID", "Descripción", "Paradas", "Es Interprovincial"};
            //seteamos las columnas
            modeloTabla.setColumnIdentifiers(titulos);
            List<Ruta> listaRutas = rutaController.listarRutas();
            if (listaRutas != null) {
                for (Ruta ruta : listaRutas) {
                    Object[] objeto = {ruta.getId(), ruta.getDescripcion(), ruta.getParadas(), ruta.isEsInterprovincial()};
                    modeloTabla.addRow(objeto);
                }
            }

            tablaRutasCompletas.setModel(modeloTabla);
        } catch (SQLException ex) {
            Logger.getLogger(JFRuta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarRuta(int idRuta) {
        try {
            Ruta ruta = rutaController.obtenerRuta(idRuta);
            txtEditDescripcion.setText(ruta.getDescripcion());
            txtEditListaParadas.setText(ruta.getParadas());
            if (ruta.isEsInterprovincial() == true) {
                cmbEditTipoRuta.setSelectedIndex(0);
            } else {
                cmbEditTipoRuta.setSelectedIndex(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JFRuta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
